/* read1411Server.c
   Generated by gSOAP 2.8.129 for read1411.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "read1411H.h"

SOAP_SOURCE_STAMP("@(#) read1411Server.c ver 2.8.129 2023-08-06 00:04:56 GMT")
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap->mode |= SOAP_XML_STRICT;
	(void)soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "rd1411:readObj1411"))
		return soap_serve_rd1411__readObj1411(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_rd1411__readObj1411(struct soap *soap)
{	struct rd1411__readObj1411 soap_tmp_rd1411__readObj1411;
	struct rd1411__readObj1411Response soap_tmp_rd1411__readObj1411Response;
	char * soap_tmp_string;
	soap_default_rd1411__readObj1411Response(soap, &soap_tmp_rd1411__readObj1411Response);
	soap_tmp_string = NULL;
	soap_tmp_rd1411__readObj1411Response.result = &soap_tmp_string;
	soap_default_rd1411__readObj1411(soap, &soap_tmp_rd1411__readObj1411);
	if (!soap_get_rd1411__readObj1411(soap, &soap_tmp_rd1411__readObj1411, "rd1411:readObj1411", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = rd1411__readObj1411(soap, soap_tmp_rd1411__readObj1411.obj, soap_tmp_rd1411__readObj1411Response.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_rd1411__readObj1411Response(soap, &soap_tmp_rd1411__readObj1411Response);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_rd1411__readObj1411Response(soap, &soap_tmp_rd1411__readObj1411Response, "rd1411:readObj1411Response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_rd1411__readObj1411Response(soap, &soap_tmp_rd1411__readObj1411Response, "rd1411:readObj1411Response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of read1411Server.c */
