/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jwitsmlparser14x_JWitsmlParserLoaderTest */

#ifndef _Included_org_jwitsmlparser14x_JWitsmlParserLoaderTest
#define _Included_org_jwitsmlparser14x_JWitsmlParserLoaderTest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
