/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jwitsmlparser14x_JWitsmlParserLoader */

#ifndef _Included_org_jwitsmlparser14x_JWitsmlParserLoader
#define _Included_org_jwitsmlparser14x_JWitsmlParserLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    init
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_init
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    parser
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_parser
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    parserJson
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_parserJson
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    parserFromFile
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_parserFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    parserFromFileJson
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_parserFromFileJson
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    saveToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_saveToFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    saveToFileJSON
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_saveToFileJSON
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    getError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_getError
  (JNIEnv *, jobject);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    getBinaryBsonVersion
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_getBinaryBsonVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    baseMsgList
 * Signature: ()Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_baseMsgList
  (JNIEnv *, jobject);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_close
  (JNIEnv *, jobject);

/*
 * Class:     org_jwitsmlparser14x_JWitsmlParserLoader
 * Method:    isClosed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_jwitsmlparser14x_JWitsmlParserLoader_isClosed
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
