/* delete1411Server.c
   Generated by gSOAP 2.8.135 for delete1411.h

gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "delete1411H.h"

SOAP_SOURCE_STAMP("@(#) delete1411Server.c ver 2.8.135 2024-10-31 23:08:15 GMT")
/*
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}
*/
#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap->mode |= SOAP_XML_STRICT;
	(void)soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "dl1411:deleteObj1411"))
		return soap_serve_dl1411__deleteObj1411(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_dl1411__deleteObj1411(struct soap *soap)
{	struct dl1411__deleteObj1411 soap_tmp_dl1411__deleteObj1411;
	struct dl1411__deleteObj1411Response soap_tmp_dl1411__deleteObj1411Response;
	char * soap_tmp_string;
	soap_default_dl1411__deleteObj1411Response(soap, &soap_tmp_dl1411__deleteObj1411Response);
	soap_tmp_string = NULL;
	soap_tmp_dl1411__deleteObj1411Response.result = &soap_tmp_string;
	soap_default_dl1411__deleteObj1411(soap, &soap_tmp_dl1411__deleteObj1411);
	if (!soap_get_dl1411__deleteObj1411(soap, &soap_tmp_dl1411__deleteObj1411, "dl1411:deleteObj1411", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = dl1411__deleteObj1411(soap, soap_tmp_dl1411__deleteObj1411.obj, soap_tmp_dl1411__deleteObj1411Response.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_dl1411__deleteObj1411Response(soap, &soap_tmp_dl1411__deleteObj1411Response);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_dl1411__deleteObj1411Response(soap, &soap_tmp_dl1411__deleteObj1411Response, "dl1411:deleteObj1411Response", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_dl1411__deleteObj1411Response(soap, &soap_tmp_dl1411__deleteObj1411Response, "dl1411:deleteObj1411Response", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of delete1411Server.c */
